version: '3.8'

services:
  mood-detector:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload